plan <- drake_plan(
  my.tree = TreeSim::sim.bd.taxa(n=300, numbsim=1, lambda=0.1, mu=0)[[1]],
  VisualizeData(my.tree),
  ape::ltt.plot(my.tree),
  ape::ltt.plot(my.tree, log="y"),
  yule.trees = TreeSim::sim.bd.taxa(n=300, numbsim=10, lambda=0.1, mu=0, complete=FALSE),
  par(mfcol = (c(1,2))),
  bd.trees = TreeSim::sim.bd.taxa(n=300, numbsim=10, lambda=1, mu=.9, complete=FALSE),
  ape::mltt.plot(bd.trees, log="y", legend=FALSE),
  ape::mltt.plot(yule.trees, log = "y", legend = FALSE),
  par(mfcol = (c(1,1))),
  plot_diversification(.1, 0, 1, .9),
  legend("topleft", legend=c("Birth Death", "Yule"), fill=colors),
  plot_diversification_zoom(.1, 0, 1, .9),
  legend("topleft", legend=c("Birth Death", "Yule"), fill=colors),
  plot_diversification(2, .4, .8, .4),
  legend("topleft", legend=c("Lower Speciation", "Higher Speciation"), fill=colors),
  plot_diversification(.8, .7, .2, .1),
  legend("topleft", legend=c("Lower Speciation/Extinction", "Higher Speciation/Exctinction"), fill=colors),
  plot_diversification(.35, .25, .55, .05),
  legend("topleft", legend=c("Dissimilar", "Similar"), fill=colors),
  )

hisse_plan <- drake_plan(
  speciation.rates = c(0.1, 0.1, 0.1, 0.2),
  extinction.rates = rep(0.03, 4),
  transition.rates = c(0.01,0.01,0, 0.01, 0, 0.01, 0.01,0,0.01, 0,0.01,0.01),
  pars = c(speciation.rates, extinction.rates, transition.rates),
  phy = tree.musse(pars, max.taxa=50, x0=1, include.extinct=FALSE),
  sim.dat.true = data.frame(names(phy$tip.state), phy$tip.state),
  sim.dat = sim.dat.true,
  sim.dat[sim.dat[,2]==3,2] = 1,
  sim.dat[sim.dat[,2]==4,2] = 2,
  sim.dat[,2] = sim.dat[,2] - 1,
  plot(phy, cex = 0.5),
  knitr::kable(cbind(sim.dat, true.char=sim.dat.true$phy.tip.state)),
  trans.rates = TransMatMaker.old(hidden.states=TRUE),
  trans.rates,
  trans.rates.nodual = ParDrop(trans.rates, c(3,5,8,10)),
  trans.rates.nodual,
  trans.rates.nodual.equal16 = ParEqual(trans.rates.nodual, c(1,6)),
  trans.rates.nodual.equal16,
  trans.rates.nodual.allequal = ParEqual(trans.rates.nodual, c(1,2,1,3,1,4,1,5,1,6,1,7,1,8)),
  trans.rates.nodual.allequal,
  trans.rates.nodual.allequal = trans.rates.nodual,
  trans.rates.nodual.allequal[!is.na(trans.rates.nodual.allequal) & !trans.rates.nodual.allequal == 0] = 1,
  trans.rates.nodual.allequal,
  trans.rates.bisse = TransMatMaker.old(hidden.states=FALSE),
  trans.rates.bisse,
  eps.anc = c(0,0,0,0),
  turnover.anc = c(1,2,3,4),
  pp = hisse.old(phy, sim.dat, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover.anc,
                 eps.anc=eps.anc, trans.rate=trans.rates.nodual.allequal),
  pp = hisse.old(phy, sim.dat, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover.anc,
                 eps.anc=eps.anc, trans.rate=trans.rates.nodual.allequal, output.type="net.div"),
  turnover.anc = c(1,1,2,2),
  eps.anc = c(1,1,2,2),
  trans.rates = TransMatMaker.old(hidden.states=TRUE),
  trans.rates.nodual = ParDrop(trans.rates, c(3,5,8,10)),
  trans.rates.nodual.allequal = ParEqual(trans.rates.nodual, c(1,2,1,3,1,4,1,5,1,6,1,7,1,8)),
  trans.rates.nodual.allequal,
  trans.rates.nodual.threerates = trans.rates.nodual,
  to.change = cbind(c(1,3), c(2,4)),
  trans.rates.nodual.threerates[to.change] = 1,
  to.change = cbind(c(2,4), c(1,3)),
  trans.rates.nodual.threerates[to.change] = 2,
  to.change = cbind(c(1,3,2,4), c(3,1,4,2)),
  trans.rates.nodual.threerates[to.change] = 3,
  trans.rates.nodual.threerates,
  pp = hisse.old(phy, sim.dat, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover.anc,
             eps.anc=eps.anc, trans.rate=trans.rates.nodual.allequal),
  load("testrecon1.rda"),
  class(pp.recon),
  pp.recon,
  plot.hisse.states(pp.recon, rate.param="net.div", show.tip.label=FALSE),
  plot.hisse.states(pp.recon, rate.param="net.div", show.tip.label=FALSE, rate.range=c(0,0.072)),
  pp.recon$aic,
  hisse.results.list = list(),
  load("testrecon1.rda"),
  hisse.results.list[[1]] = pp.recon,
  load("testrecon2.rda"),
  hisse.results.list[[2]] = pp.recon,
  load("testrecon3.rda"),
  hisse.results.list[[3]] = pp.recon,
  # Now supply the list the plotting function
  plot.hisse.states(hisse.results.list, rate.param="net.div", show.tip.label=FALSE, rate.range=c(0,0.072))
)
